c-list: don't use elvis operator for c_list_entry() macro
Visual Studio 2017 does not support "?:":

  ../tests/test-embed.c(31): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
  ../tests/test-embed.c(31): error C2059: syntax error: ':'

Without elvis operator and gcc's expression statements, it is harder
to write a macro that evaluates "what" only once.

Use a static inline function instead.

Signed-off-by: Thomas Haller <thaller@redhat.com>
Signed-off-by: David Rheinsberg <david.rheinsberg@gmail.com>